config/routes.rb
Polling::Application.routes.draw do
  root to: 'polls#index'
  resources :polls
  resources :items
  resources :votes

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :votes, :dependent => :destroy
  belongs_to :poll
  attr_accessible :content, :poll_id
  validates_presence_of :content, :poll_id
  validate :check_poll_items

  def check_poll_items
  	errors.add(:votes, "You cannot have more than 5 items") unless self.poll.items.count < 5
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :items, :dependent => :destroy
	has_many :votes, :through => :items
  attr_accessible :name, :question
  accepts_nested_attributes_for :items
  validate :items_count, :on => :update
  validates :question, :presence => true

  def items_count
  	errors.add(:items, "must be between 2 and 5.") if (self.items.count <= 1 || self.items.count >= 6)
  end

  def has_ip?(given_ip)
  	self.votes.find_by_ip_address(given_ip)
  end

  def has_votes?
  	self.votes.any?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :item
  attr_accessible :ip_address, :item_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.where(:poll_id => params[:poll_id])
  	render json: @items
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      render json: @item, status: :created, location: @item
    else
			render json: @item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    head :no_content
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @polls }
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])
    
    if !@poll.has_ip?(request.remote_ip)
      flash[:error] = "You must vote before you can see the results"
      redirect_to polls_path
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find(params[:id])
    redirect_to polls_path if @poll.has_votes?
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(params[:poll])

    respond_to do |format|
      if @poll.save
        format.html { redirect_to edit_poll_path(@poll), notice: 'You must set your poll answers.' }
        format.json { render json: @poll, status: :created, location: @poll }
      else
        format.html { render action: "new" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to polls_path, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def new
		@poll = Poll.find(params[:poll])
		@vote = Vote.new(:ip_address => request.remote_ip, :item_id => 24)

		@poll.items_count
		if @poll.errors.any?
			flash[:error] = "Sorry, this is an invalid poll. Please make sure the poll has between 2 and 5 items."
			redirect_to edit_poll_path(@poll)
		end
	end

	def create
		@vote = Vote.new(params[:vote])
		@poll = Item.find(@vote.item_id).poll
		if @poll.has_ip?(@vote.ip_address)
			flash[:error] = 'You have already voted in this poll.'
			redirect_to polls_path
		else
			if @vote.save
				redirect_to poll_path(@poll), :notice => 'Vote cast successfully!'
			else
				render action: 'new'
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polling</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :question, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<div class="page-header">
  <h1>Editing "<%= @poll.name %>"</h1>
</div>
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-actions">
    <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :question, :class => 'text_field' %>
    </div>
  </div>
<% end %>

<h3>Items</h3>

<ul id="items">
</ul>

<form id="addition">
  <input id="content" name="item[content]" type="text">
  <input id="poll_id" name="item[poll_id]" type="hidden" value="<%= params[:id] %>">
  <input type="submit" value="Add Item">
</form>

<p id="error"></p>

app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:created_on)%></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.name %></td>
        <td><%= poll.question %></td>
        <td><%= poll.created_at.strftime('%B %d, %Y') if poll.created_at %></td>
        <td>
          <%= link_to 'Vote', new_vote_path(:poll => poll), :class => 'btn btn-mini btn-info' unless poll.has_ip?(request.remote_ip) %>
          <%= link_to 'See Results', poll_path(poll), :class => 'btn btn-inverse btn-mini' if poll.has_ip?(request.remote_ip) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_poll_path(poll), :class => 'btn btn-mini' unless poll.has_votes? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_path(poll),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1>New Poll</h1>
</div>

<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :question, :class => 'text_field' %>
    </div>
  </div>

	<div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/show.html.erb
<div class="page-header">
  <h1><%=@poll.name %> - Results</h1>
</div>
<h3><%= @poll.question %></h3>
<table class="table table-hover">
	<tr>
		<th># of Votes</th>
		<th>Answer</th>
	</tr>
	<% @poll.items.each do |i| %>
		<tr>
			<td><%= i.votes.count %></td>
			<td><%= i.content %></td>
		</tr>
	<% end %>
</table>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to 'Delete Poll',
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/votes/new.html.erb
<div class="page-header">
  <h1><%=@poll.name %></h1>
</div>
<h3><%= @poll.question %></h3>

<%= form_for(@vote) do |f| %>
  <% @poll.items.each do |i| %>
    <%= f.radio_button :item_id, i.id %>
    <%= f.label :item_id, i.content %>
  <% end %>
  <%= f.hidden_field :ip_address %>
  
  <div class="form-actions">
    <%= f.submit 'Vote', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>